const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  FINANCIAL_LOADING: 'FINANCIAL_LOADING',
  FINANCIAL_ALL: 'FINANCIAL_ALL',
  FINANCIAL_CREATE: 'FINANCIAL_CREATE',
  FINANCIAL_UPDATE: 'FINANCIAL_UPDATE',
  FINANCIAL_EDIT: 'FINANCIAL_EDIT',
  FINANCIAL_ID: 'FINANCIAL_ID',
  FINANCIAL_REMOVE: 'FINANCIAL_REMOVE',
  FINANCIAL_UPLOAD: 'FINANCIAL_UPLOAD',

  CLIENT_LOADING: 'CLIENT_LOADING',
  CLIENT_ALL: 'CLIENT_ALL',
  CLIENT_LIST_ASSET: 'CLIENT_LIST_ASSET',
  CLIENT_EDIT: 'CLIENT_EDIT',
  CLIENT_ID: 'CLIENT_ID',
  CLIENT_UPLOAD: 'CLIENT_UPLOAD',

  TRANSACTION_LOADING: 'TRANSACTION_LOADING',
  TRANSACTION_ALL_USER: 'TRANSACTION_ALL_USER',
  TRANSACTION_USER_ID: 'TRANSACTION_USER_ID',
  TRANSACTION_CREATE: 'TRANSACTION_CREATE',
  TRANSACTION_UPLOAD: 'TRANSACTION_UPLOAD',
  TRANSACTION_BANK_DEPOSIT: 'TRANSACTION_BANK_DEPOSIT',

  ACCOUNT_LOADING: 'ACCOUNT_LOADING',
  ACCOUNT_ALL: 'ACCOUNT_ALL',
  ACCOUNT_ID: 'ACCOUNT_ID',
  ACCOUNT_BALANCE: 'ACCOUNT_BALANCE',
  ACCOUNT_UPLOAD: 'ACCOUNT_UPLOAD',
  ACCOUNT_EDIT: 'ACCOUNT_EDIT',
  
  BANK_LOADING: 'BANK_LOADING',
  ALL_BANK: 'ALL_BANK'
}

export default TYPES
