const TYPES = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  FINANCIAL_LOADING: 'FINANCIAL_LOADING',
  FINANCIAL_ALL: 'FINANCIAL_ALL',
  FINANCIAL_CREATE: 'FINANCIAL_CREATE',
  FINANCIAL_UPDATE: 'FINANCIAL_UPDATE',
  FINANCIAL_EDIT: 'FINANCIAL_EDIT',
  FINANCIAL_ID: 'FINANCIAL_ID',
  FINANCIAL_REMOVE: 'FINANCIAL_REMOVE',
  FINANCIAL_UPLOAD: 'FINANCIAL_UPLOAD',

  CLIENT_LOADING: 'CLIENT_LOADING',
  CLIENT_ALL: 'CLIENT_ALL',
  CLIENT_EDIT: 'CLIENT_EDIT',
  CLIENT_ID: 'CLIENT_ID',
  CLIENT_UPLOAD: 'CLIENT_UPLOAD'
}

export default TYPES
